### PR TITLE
fix(wallet): restore scans all keysets including inactive

### LINKED ISSUE #1752: cdk-restore inactive keysets issue
## Description

`fn restore()` in `wallet/mod.rs` only scans active keysets. If a mint has rotated keysets, proofs signed with the old (now inactive) keyset are never found during restore.

`restore()` should iterate all keysets for the wallet's unit, not just active ones. The `active` filter makes sense for normal operations (you want to mint with the current keyset), but during restore you need to scan everything.

Could be a separate method like `get_all_mint_keysets()` that skips the `keyset.active` check, or just an optional parameter on the existing one.

### PR DESCRIPTION
**Pull request by Forte11Cuba**
### Description

restore() in wallet/mod.rs only scanned active keysets via load_mint_keysets(). If a mint has rotated keysets, proofs signed with the old (now inactive) keyset were never found during restore.

Added get_all_mint_keysets() which returns all keysets for the wallet's unit regardless of active status, and updated restore() to use it.

Closes #1752     

-----

### Notes to the reviewers
            
The fix is minimal a new method get_all_mint_keysets() in keysets.rs that drops the keyset.active filter, and a one-line change in restore() to call it. The active filter remains correct for all other operations (mint, swap, melt) where you want the current keyset.  - cdk: restore() now scans inactive keysets so proofs from rotated keysets are recovered                                                              

-----

#### FIXED

- cdk: restore() now scans inactive keysets so proofs from rotated keysets are recovered

----

### Checklist

* [x] I followed the [code style guidelines](https://github.com/cashubtc/cdk/blob/main/CODE_STYLE.md)
* [ ] I ran `just final-check` before committing

### CODE REVIEW

File: crates/cdk/src/wallet/keysets.rs [hunk 1]
```diff
@@ -64,6 +64,38 @@ impl Wallet {
...
+            })
+            .collect::<Vec<_>>();
+
+        if !keysets.is_empty() {
+            Ok(keysets)
+        } else {
+            Err(Error::UnknownKeySet)
+        }
+    }
+
```
Comment (lescuer97) [inline crates/cdk/src/wallet/keysets.rs]: maybe it would be better to change the contract for `get_mint_keysets` to have `only_active` boolean param. this way we don't repeat that much code

Comment (Forte11Cuba) [reply crates/cdk/src/wallet/keysets.rs]: You're right. I'll fix it.

File: crates/cdk/src/wallet/keysets.rs [hunk 2]
```diff
@@ -29,16 +29,18 @@ impl Wallet {
...
     ///
     /// Checks the metadata cache for keysets. If cache is not populated,
-    /// fetches from mint and updates cache. Returns error if no active keysets found.
+    /// fetches from mint and updates cache. When `only_active` is true,
+    /// returns only active keysets; when false, returns all keysets
+    /// (e.g. for restore, which needs to scan rotated keysets).
     #[instrument(skip(self))]
     #[inline(always)]
-    pub async fn get_mint_keysets(&self) -> Result<Vec<KeySetInfo>, Error> {
+    pub async fn get_mint_keysets(&self, only_active: bool) -> Result<Vec<KeySetInfo>, Error> {
```
Comment (lescuer97) [inline crates/cdk/src/wallet/keysets.rs]: wait for @thesimplekid  to say something but he might prefer a struct for the flag. It makes it clearer for when calling the function

File: crates/cdk/src/wallet/keysets.rs [hunk 3]
```diff
@@ -49,7 +60,12 @@ impl Wallet {
             .keysets
             .values()
             .filter_map(|keyset| {
-                if keyset.unit == self.unit && keyset.active {
+                let dominated = keyset.unit == self.unit;
+                let dominated = match filter {
+                    KeysetFilter::Active => dominated && keyset.active,
+                    KeysetFilter::All => dominated,
+                };
+                if dominated {
```
Comment (thesimplekid) [inline crates/cdk/src/wallet/keysets.rs]: I think dominated is unclear and we can make this cleaner using early returns. 

```rust
if keyset.unit != self.unit {
    return None;
}

if matches!(filter, KeysetFlter::Active) && !keyset.active {
    return None;
}

Some((*keyset.clone()).clone())

````
