### PR TITLE
Fix websocket issues and mint quotes

### LINKED ISSUE #1209: Fix issue with websocket
When checking the status of a mint quote form the websocket the check only happens against the database and not the processor,  it should be similar to `check_mint_quote` and not only the database.

Also address these logings

Image

### PR DESCRIPTION
**Pull request by crodas**
### Description

Fixes #1209 and #1104

When checking with HTTP pulling, mint quotes would ping the ln backend if needed to get any payment that may not be included, so the mint uses this chance to correct its database.

This check was missing for database subscriptions
-----

### Notes to the reviewers

-----

#### FIXED

----

### Checklist

* [ ] I followed the [code style guidelines](https://github.com/cashubtc/cdk/blob/main/CODE_STYLE.md)
* [ ] I ran `just final-check` before committing

### CODE REVIEW

File: crates/cdk/src/mint/subscription.rs [hunk 1]
```diff
@@ -1,27 +1,54 @@
...
 
 /// Mint subtopics
 #[derive(Clone)]
 pub struct MintPubSubSpec {
     db: DynMintDatabase,
+    payment_processors: Arc<HashMap<PaymentProcessorKey, DynMintPayment>>,
 }
 
 impl MintPubSubSpec {
+    /// Similar to Mint::check_mint_quote_paid, but copied to avoid
```
Comment (thesimplekid) [inline crates/cdk/src/mint/subscription.rs]: I think this comment is cut off?

**Review by thesimplekid — COMMENTED** [review]
Nice looks good just think one doc comment needs to be fixed.

File: crates/cdk/src/mint/subscription.rs (hunk 1 above)
Comment (crodas) [reply crates/cdk/src/mint/subscription.rs]: Yeah, that was the old doc-doc from a previous approach. Lemme update it.
